name: push_to_staging
on: 
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
  
    - name: Check out dev repo
      uses: actions/checkout@v4
      with:
        path: dev
        persist-credentials: false
    
    - name: Checkout Staging Repo
      uses: actions/checkout@v4
      with:
        path: staging
        repository: juskalalie/hgdb-dev-staging
        persist-credentials: true
        token: ${{ secrets.STAGING_REPO_TOKEN }}

    - name: Update addon verison number
      run: |
          python3 staging/update.py dev staging

    - name: Log in to the Container registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Staging Addon image
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target dev/hassio-filenio-backup \
          --docker-hub "ghcr.io/juskalalie"

    - name: Publish Staging Addon Version
      run: |
          cd staging
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updating staging addon config"
          git push
